apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-deployment
  labels:
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.7
          env:
            - name: MARIADB_USER
              valueFrom: 
                secretKeyRef: 
                  name: maria-secret
                  key: maria-user 
            - name: MARIADB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: maria-secret
                  key: maria-password 
            - name: MARIADB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: maria-secret
                  key: maria-root-password 
          ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  type: NodePort
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
