apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpbb-deployment
  labels:
    app: phpbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpbb
  template:
    metadata:
      labels:
        app: phpbb
    spec:
      containers:
        - name: phpbb
          image: bitnami/phpbb:latest
          env:
            - name: PHPBB_DATABASE_USER
              valueFrom: 
                secretKeyRef: 
                  name: maria-secret
                  key: maria-user 
            - name: PHPBB_DATABASE_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: maria-secret
                  key: maria-password
            - name: PHPBB_DATABASE_NAME
              value: phpbb
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: PHPBB_DATABASE_HOST
              valueFrom:
                configMapKeyRef: 
                  name: maria-config
                  key: maria-url
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: phpbb-service
spec:
  type: NodePort
  selector:
    app: phpbb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
